import { Router } from 'express';
import bcrypt from 'bcryptjs';
import { z } from 'zod';
import PDFDocument from 'pdfkit';
import XLSX from 'xlsx';
import fs from 'fs';
import path from 'path';
import { prisma } from '../lib/prisma.js';
import { AuthRequest, auth, sign } from '../middleware/auth.js';
import { amountToFrench, calcLine, calcTotals } from '../lib/money.js';
import { nextNumber } from '../services/numbering.js';
export const router = Router();
const audit = (req: AuthRequest, action: string, entity: string, entityId?: string, details?: unknown) => prisma.auditLog.create({ data: { userId: req.user?.id, action, entity, entityId, details: details ? JSON.stringify(details) : undefined } }).catch(() => undefined);
router.post('/auth/login', async (req, res) => { const body = z.object({ login: z.string(), password: z.string() }).parse(req.body); const user = await prisma.user.findFirst({ where: { OR: [{ email: body.login }, { username: body.login }], active: true }, include: { role: true } }); if (!user || !(await bcrypt.compare(body.password, user.passwordHash))) return res.status(401).json({ message: 'Identifiants invalides' }); await prisma.auditLog.create({ data: { userId: user.id, action: 'Login', entity: 'User', entityId: String(user.id) } }); res.json({ token: sign({ id: user.id, role: user.role.name }), user: { id: user.id, email: user.email, fullName: user.fullName, role: user.role.name } }); });
router.use(auth);
router.get('/company', async (_req, res) => res.json(await prisma.company.upsert({ where: { id: 1 }, create: { id: 1, logoPath: '/assets/logo-selka-cme.jpg' }, update: {} })));
router.put('/company', async (req: AuthRequest, res) => { const company = await prisma.company.upsert({ where: { id: 1 }, create: { id: 1, ...req.body }, update: req.body }); await audit(req, 'Edit', 'Company', '1'); res.json(company); });
function crud(model: any, entity: string, searchFields: string[]) { router.get(`/${entity}`, async (req, res) => { const q = String(req.query.q || ''); const page = Number(req.query.page || 1), take = Number(req.query.take || 20); const where = q ? { OR: searchFields.map((field) => ({ [field]: { contains: q } })) } : {}; const [items, total] = await Promise.all([model.findMany({ where, skip: (page - 1) * take, take, orderBy: { id: 'desc' } }), model.count({ where })]); res.json({ items, total, page, take }); }); router.post(`/${entity}`, async (req: AuthRequest, res) => { const item = await model.create({ data: req.body }); await audit(req, 'Create', entity, String(item.id), req.body); res.status(201).json(item); }); router.put(`/${entity}/:id`, async (req: AuthRequest, res) => { const item = await model.update({ where: { id: Number(req.params.id) }, data: req.body }); await audit(req, 'Edit', entity, req.params.id, req.body); res.json(item); }); router.delete(`/${entity}/:id`, async (req: AuthRequest, res) => { const item = await model.update({ where: { id: Number(req.params.id) }, data: { archived: true } }).catch(() => model.delete({ where: { id: Number(req.params.id) } })); await audit(req, 'Archive', entity, req.params.id); res.json(item); }); }
crud(prisma.client, 'clients', ['name', 'code', 'nif']); crud(prisma.product, 'products', ['designation', 'reference', 'barcode']); crud(prisma.category, 'categories', ['name']);
function mapLine(line: any) { const c = calcLine(line); return { productId: line.productId ? Number(line.productId) : undefined, reference: line.reference, designation: line.designation, quantity: line.quantity, unit: line.unit || 'U', priceHt: line.priceHt, discountRate: line.discountRate || 0, vatRate: line.vatRate || 0, totalHt: c.totalHt, vatAmount: c.vatAmount, totalTtc: c.totalTtc }; }
async function createDoc(kind: 'FAC'|'DEV'|'BC', body: any) { const items = body.items || []; const totals = calcTotals(items, body.stamp || 0); const number = body.number || await nextNumber(kind); if (kind === 'FAC') return prisma.invoice.create({ data: { number, date: new Date(body.date || Date.now()), dueDate: body.dueDate ? new Date(body.dueDate) : undefined, clientId: Number(body.clientId), status: body.status || 'Brouillon', totalHt: totals.totalHt, discountTotal: totals.discountTotal, vatTotal: totals.vatTotal, stamp: totals.stamp, totalTtc: totals.totalTtc, remaining: totals.totalTtc, amountWords: amountToFrench(totals.totalTtc), items: { create: items.map(mapLine) } }, include: { items: true, client: true } }); if (kind === 'DEV') return prisma.quote.create({ data: { number, date: new Date(body.date || Date.now()), validUntil: body.validUntil ? new Date(body.validUntil) : undefined, clientId: Number(body.clientId), status: body.status || 'Brouillon', totalHt: totals.totalHt, vatTotal: totals.vatTotal, totalTtc: totals.totalTtc, items: { create: items.map(mapLine) } }, include: { items: true, client: true } }); return prisma.purchaseOrder.create({ data: { number, date: new Date(body.date || Date.now()), clientId: Number(body.clientId), quoteId: body.quoteId, totalHt: totals.totalHt, vatTotal: totals.vatTotal, totalTtc: totals.totalTtc, items: { create: items.map(mapLine) } }, include: { items: true, client: true } }); }
router.get('/invoices', async (_req, res) => res.json(await prisma.invoice.findMany({ include: { client: true, payments: true }, orderBy: { id: 'desc' } }))); router.post('/invoices', async (req: AuthRequest, res) => { const doc = await createDoc('FAC', req.body); await audit(req, 'Create', 'Invoice', String(doc.id)); res.status(201).json(doc); }); router.post('/invoices/:id/validate', async (req: AuthRequest, res) => { const inv = await prisma.invoice.update({ where: { id: Number(req.params.id) }, data: { status: 'Validée' } }); await audit(req, 'Validate', 'Invoice', req.params.id); res.json(inv); });
router.get('/payments', async (_req, res) => res.json(await prisma.payment.findMany({ include: { client: true, invoice: true }, orderBy: { id: 'desc' } }))); router.post('/payments', async (req: AuthRequest, res) => { const inv = await prisma.invoice.findUniqueOrThrow({ where: { id: Number(req.body.invoiceId) } }); const payment = await prisma.payment.create({ data: { invoiceId: inv.id, clientId: inv.clientId, amount: req.body.amount, mode: req.body.mode, reference: req.body.reference, banque: req.body.banque, notes: req.body.notes } }); const payments = await prisma.payment.findMany({ where: { invoiceId: inv.id } }); const paid = payments.reduce((sum, p) => sum + Number(p.amount), 0); const remaining = Math.max(0, Number(inv.totalTtc) - paid); await prisma.invoice.update({ where: { id: inv.id }, data: { paid, remaining, status: remaining === 0 ? 'Payée' : paid > 0 ? 'Partiellement payée' : inv.status } }); await audit(req, 'Payment', 'Invoice', String(inv.id), req.body); res.status(201).json(payment); });
router.get('/quotes', async (_req, res) => res.json(await prisma.quote.findMany({ include: { client: true }, orderBy: { id: 'desc' } }))); router.post('/quotes', async (req: AuthRequest, res) => { const doc = await createDoc('DEV', req.body); await audit(req, 'Create', 'Quote', String(doc.id)); res.status(201).json(doc); }); router.post('/quotes/:id/convert-to-bc', async (req: AuthRequest, res) => { const quote = await prisma.quote.findUniqueOrThrow({ where: { id: Number(req.params.id) }, include: { items: true } }); const bc = await createDoc('BC', { clientId: quote.clientId, quoteId: quote.id, items: quote.items }); await prisma.quote.update({ where: { id: quote.id }, data: { status: 'Converti' } }); await audit(req, 'Create', 'PurchaseOrder', String(bc.id)); res.json(bc); });
router.get('/purchase-orders', async (_req, res) => res.json(await prisma.purchaseOrder.findMany({ include: { client: true }, orderBy: { id: 'desc' } }))); router.post('/purchase-orders', async (req: AuthRequest, res) => { const doc = await createDoc('BC', req.body); await audit(req, 'Create', 'PurchaseOrder', String(doc.id)); res.status(201).json(doc); }); router.post('/purchase-orders/:id/convert-to-bl', async (req: AuthRequest, res) => { const bc = await prisma.purchaseOrder.findUniqueOrThrow({ where: { id: Number(req.params.id) }, include: { items: true } }); const bl = await prisma.deliveryNote.create({ data: { number: await nextNumber('BL'), date: new Date(), clientId: bc.clientId, purchaseOrderId: bc.id, items: { create: bc.items.map((i) => ({ productId: i.productId, reference: i.reference, designation: i.designation, quantity: i.quantity, unit: i.unit })) } }, include: { items: true, client: true } }); await audit(req, 'Create', 'DeliveryNote', String(bl.id)); res.json(bl); });
router.get('/delivery-notes', async (_req, res) => res.json(await prisma.deliveryNote.findMany({ include: { client: true }, orderBy: { id: 'desc' } }))); router.post('/delivery-notes', async (req: AuthRequest, res) => { const bl = await prisma.deliveryNote.create({ data: { number: req.body.number || await nextNumber('BL'), date: new Date(req.body.date || Date.now()), clientId: Number(req.body.clientId), observations: req.body.observations, signature: req.body.signature, items: { create: (req.body.items || []).map((i: any) => ({ productId: i.productId ? Number(i.productId) : undefined, reference: i.reference, designation: i.designation, quantity: i.quantity, unit: i.unit || 'U' })) } }, include: { client: true, items: true } }); await audit(req, 'Create', 'DeliveryNote', String(bl.id)); res.status(201).json(bl); });
router.get('/credit-notes', async (_req, res) => res.json(await prisma.creditNote.findMany({ include: { client: true, invoice: true }, orderBy: { id: 'desc' } }))); router.post('/credit-notes', async (req: AuthRequest, res) => { const items = req.body.items || []; const totals = calcTotals(items, 0); const credit = await prisma.creditNote.create({ data: { number: req.body.number || await nextNumber('AV'), date: new Date(req.body.date || Date.now()), clientId: Number(req.body.clientId), invoiceId: req.body.invoiceId ? Number(req.body.invoiceId) : undefined, reason: req.body.reason || 'Avoir commercial', totalHt: totals.totalHt, vatTotal: totals.vatTotal, totalTtc: totals.totalTtc, items: { create: items.map((line: any) => { const c = calcLine(line); return { productId: line.productId, reference: line.reference, designation: line.designation, quantity: line.quantity, unit: line.unit || 'U', priceHt: line.priceHt, vatRate: line.vatRate || 0, totalHt: c.totalHt, vatAmount: c.vatAmount, totalTtc: c.totalTtc }; }) } } }); await audit(req, 'Create', 'CreditNote', String(credit.id)); res.status(201).json(credit); });
router.get('/dashboard', async (_req, res) => { const [invoices, payments, quotes] = await Promise.all([prisma.invoice.findMany(), prisma.payment.findMany(), prisma.quote.count({ where: { status: 'Envoyé' } })]); const sum = (arr: any[], key: string) => arr.reduce((s, x) => s + Number(x[key]), 0); res.json({ cards: { chiffreAffaires: sum(invoices, 'totalHt'), totalFacture: sum(invoices, 'totalTtc'), totalEncaisse: sum(payments, 'amount'), totalImpaye: sum(invoices, 'remaining'), tvaCollectee: sum(invoices, 'vatTotal'), nombreFactures: invoices.length, facturesEnRetard: invoices.filter((i) => i.dueDate && i.dueDate < new Date() && Number(i.remaining) > 0).length, devisEnAttente: quotes }, charts: { monthly: invoices.map((i) => ({ date: i.date.toISOString().slice(0, 10), total: Number(i.totalTtc), vat: Number(i.vatTotal) })), payments: payments.map((p) => ({ date: p.date.toISOString().slice(0, 10), total: Number(p.amount) })) } }); });
router.get('/reports/:type', async (req, res) => { const data = req.params.type === 'payments' ? await prisma.payment.findMany({ include: { client: true, invoice: true } }) : await prisma.invoice.findMany({ include: { client: true } }); if (req.query.format === 'xlsx') { const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(JSON.parse(JSON.stringify(data))), req.params.type); return res.setHeader('Content-Disposition', `attachment; filename=${req.params.type}.xlsx`).send(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' })); } res.json(data); });
router.get('/invoices/:id/pdf', async (req, res) => { const inv = await prisma.invoice.findUniqueOrThrow({ where: { id: Number(req.params.id) }, include: { client: true, items: true } }); const company = await prisma.company.findUnique({ where: { id: 1 } }); const doc = new PDFDocument({ size: 'A4', margin: 40 }); res.setHeader('Content-Type', 'application/pdf'); doc.pipe(res); const logo = path.resolve('public/assets/logo-selka-cme.jpg'); if (fs.existsSync(logo)) doc.image(logo, 40, 30, { width: 120 }); doc.fontSize(18).fillColor('#092F5F').text(company?.raisonSociale || 'EURL SELKA C.M.E', 180, 40).fontSize(10).fillColor('#1F2937').text(company?.activite || 'COMMERCE MULTIPLE ET ENTREPRISES', 180, 65); doc.fontSize(22).fillColor('#F5224A').text('FACTURE', 40, 130); doc.fontSize(10).fillColor('#1F2937').text(`N° ${inv.number}\nDate: ${inv.date.toISOString().slice(0,10)}\nClient: ${inv.client.name}`, 40, 165); let y = 230; doc.text('Référence  Désignation  Qté  Unité  Prix HT  Remise  TVA  Total HT', 40, y); y += 20; inv.items.forEach((item) => { doc.text(`${item.reference || ''}  ${item.designation.slice(0,24)}  ${item.quantity}  ${item.unit}  ${item.priceHt}  ${item.discountRate}%  ${item.vatRate}%  ${item.totalHt}`, 40, y); y += 18; }); doc.text(`Total HT: ${inv.totalHt}\nTVA: ${inv.vatTotal}\nTimbre: ${inv.stamp}\nNet à payer: ${inv.totalTtc}`, 380, y + 20); doc.text(`Arrêtée la présente facture à la somme de : ${inv.amountWords}`, 40, y + 110, { width: 500 }); doc.end(); });
router.get('/search', async (req, res) => { const q = String(req.query.q || ''); const [clients, products, invoices] = await Promise.all([prisma.client.findMany({ where: { OR: [{ name: { contains: q } }, { nif: { contains: q } }, { code: { contains: q } }] }, take: 10 }), prisma.product.findMany({ where: { OR: [{ designation: { contains: q } }, { reference: { contains: q } }] }, take: 10 }), prisma.invoice.findMany({ where: { number: { contains: q } }, take: 10 })]); res.json({ clients, products, invoices }); });
router.post('/backup', async (req: AuthRequest, res) => { const src = path.resolve('prisma/dev.db'), file = `backup-${Date.now()}.sqlite`, dest = path.resolve('backups', file); if (fs.existsSync(src)) fs.copyFileSync(src, dest); await audit(req, 'Backup', 'Database', file); res.json({ file }); });
router.post('/restore', async (req: AuthRequest, res) => { const file = path.basename(req.body.file); fs.copyFileSync(path.resolve('backups', file), path.resolve('prisma/dev.db')); await audit(req, 'Restore', 'Database', file); res.json({ restored: file }); });
router.get('/audit-logs', async (_req, res) => res.json(await prisma.auditLog.findMany({ include: { user: true }, orderBy: { createdAt: 'desc' }, take: 200 })));
