import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bar, BarChart, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Archive, ChartColumn, ClipboardList, FileText, LayoutDashboard, Package, Receipt, Search, Settings, Shield, Truck, Users } from 'lucide-react';
import './style.css';
const API = import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
const logo = '/logo-selka-cme.jpg';
async function api(path: string, opt: RequestInit = {}) { const token = localStorage.getItem('token'); const res = await fetch(API + path, { ...opt, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(opt.headers || {}) } }); if (!res.ok) throw new Error((await res.json().catch(() => ({ message: res.statusText }))).message); return res.headers.get('content-type')?.includes('application/json') ? res.json() : res.blob(); }
function Login({ on }: { on: () => void }) { const [login, setLogin] = useState('admin@selka.local'), [password, setPassword] = useState(''), [err, setErr] = useState(''); return <main className="login"><form className="login-card" onSubmit={async e => { e.preventDefault(); try { const r = await api('/auth/login', { method: 'POST', body: JSON.stringify({ login, password }) }); localStorage.setItem('token', r.token); on(); } catch (x: any) { setErr(x.message); } }}><img src={logo} alt="Logo EURL SELKA C.M.E"/><h1>EURL SELKA C.M.E</h1><p>COMMERCE MULTIPLE ET ENTREPRISES</p><label>Email / Username<input value={login} onChange={e => setLogin(e.target.value)} /></label><label>Mot de passe<input type="password" value={password} onChange={e => setPassword(e.target.value)} /></label><label className="inline"><input type="checkbox"/> Se souvenir de moi</label>{err && <b className="error">{err}</b>}<button>Se connecter</button></form></main>; }
const nav = [['Dashboard', LayoutDashboard], ['Factures', FileText], ['Devis', Receipt], ['Avoirs', Receipt], ['Bons de commande', ClipboardList], ['Bons de livraison', Truck], ['Clients', Users], ['Produits & Services', Package], ['Paiements', Receipt], ['Impayés', FileText], ['Rapports', ChartColumn], ['Archives', Archive], ['Paramètres', Settings], ['Administration', Shield]] as const;
function Shell() { const [page, setPage] = useState('Dashboard'); return <div className="app"><aside><img src={logo} alt="Logo"/><h2>EURL SELKA C.M.E</h2>{nav.map(([n, Icon]) => <button className={page === n ? 'active' : ''} onClick={() => setPage(n)} key={n}><Icon size={18}/>{n}</button>)}</aside><section><header><h1>{page}</h1><GlobalSearch/></header><Page page={page}/></section></div>; }
function GlobalSearch() { const [q, setQ] = useState(''), [r, setR] = useState<any>(); return <div className="search"><Search size={16}/><input placeholder="Recherche globale" value={q} onChange={async e => { setQ(e.target.value); if (e.target.value.length > 1) setR(await api('/search?q=' + encodeURIComponent(e.target.value))); }}/>{r && q && <div className="results">{Object.entries(r).map(([k, v]: any) => <p key={k}>{k}: {v.length}</p>)}</div>}</div>; }
function Page({ page }: { page: string }) { if (page === 'Dashboard') return <Dashboard/>; if (page === 'Clients') return <Crud title="Clients" path="/clients" fields={['code','type','name','firstName','adresse','wilaya','commune','telephone','email','nif','nis','rc','articleImposition','nin','paymentTerms','notes']}/>; if (page === 'Produits & Services') return <Crud title="Produits & Services" path="/products" fields={['reference','designation','description','type','unit','priceHt','vatRate','priceTtc','stock','alertThreshold','barcode','notes']}/>; if (page === 'Paiements') return <Crud title="Paiements" path="/payments" fields={['invoiceId','amount','mode','reference','banque','notes']}/>; if (page === 'Paramètres') return <SettingsPage/>; if (page === 'Rapports') return <Reports/>; if (page === 'Administration') return <Admin/>; return <Docs kind={page === 'Factures' ? 'invoices' : page === 'Devis' ? 'quotes' : page.includes('Avoir') ? 'credit-notes' : page.includes('commande') ? 'purchase-orders' : 'delivery-notes'}/>; }
function Dashboard() { const [d, setD] = useState<any>(); useEffect(() => { api('/dashboard').then(setD); }, []); if (!d) return <p>Chargement...</p>; return <><div className="filters">{['Aujourd’hui','Cette semaine','Ce mois','Ce trimestre','Cette année','Période personnalisée'].map(x => <button key={x}>{x}</button>)}</div><div className="cards">{Object.entries(d.cards).map(([k,v]) => <article key={k}><span>{k}</span><b>{Number(v).toLocaleString('fr-DZ')} DA</b></article>)}</div><div className="grid2"><div className="panel"><h3>CA par mois / TVA</h3><ResponsiveContainer height={260}><LineChart data={d.charts.monthly}><XAxis dataKey="date"/><YAxis/><Tooltip/><Line dataKey="total" stroke="#092F5F"/><Line dataKey="vat" stroke="#F5224A"/></LineChart></ResponsiveContainer></div><div className="panel"><h3>Paiements</h3><ResponsiveContainer height={260}><BarChart data={d.charts.payments}><XAxis dataKey="date"/><YAxis/><Tooltip/><Bar dataKey="total" fill="#092F5F"/></BarChart></ResponsiveContainer></div></div></>; }
function Crud({ title, path, fields }: { title: string; path: string; fields: string[] }) { const [items, setItems] = useState<any[]>([]), [form, setForm] = useState<any>({}); const load = () => api(path).then((r: any) => setItems(r.items || r)); useEffect(load, []); return <div className="panel"><h2>{title}</h2><form className="form" onSubmit={async e => { e.preventDefault(); await api(path, { method: 'POST', body: JSON.stringify(form) }); setForm({}); load(); }}>{fields.map(f => <label key={f}>{f}<input value={form[f] || ''} onChange={e => setForm({ ...form, [f]: e.target.value })}/></label>)}<button>Créer</button></form><Table rows={items}/></div>; }
function Docs({ kind }: { kind: string }) { const [rows, setRows] = useState<any[]>([]), [clients, setClients] = useState<any[]>([]), [form, setForm] = useState<any>({ items: [{ designation: 'Service', quantity: '1', unit: 'U', priceHt: '1000', discountRate: '0', vatRate: '19' }] }); const load = () => api('/' + kind).then(setRows).catch(() => setRows([])); useEffect(() => { load(); api('/clients').then((r: any) => setClients(r.items || [])); }, [kind]); return <div className="panel"><div className="actions"><button>Nouveau document</button><button onClick={() => api('/reports/invoices?format=xlsx').then((b: Blob) => download(b, 'export.xlsx'))}>Exporter</button><button onClick={() => print()}>Imprimer</button></div><form className="form" onSubmit={async e => { e.preventDefault(); await api('/' + kind, { method: 'POST', body: JSON.stringify(form) }); load(); }}><select onChange={e => setForm({ ...form, clientId: e.target.value })}><option>Choisir client</option>{clients.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select>{form.items.map((it: any, i: number) => <div className="line" key={i}>{['reference','designation','quantity','unit','priceHt','discountRate','vatRate'].map(f => <input key={f} placeholder={f} value={it[f] || ''} onChange={e => { const items = [...form.items]; items[i] = { ...it, [f]: e.target.value }; setForm({ ...form, items }); }}/>)}</div>)}<button type="button" onClick={() => setForm({ ...form, items: [...form.items, {}] })}>Ajouter ligne</button><button>Enregistrer</button></form><Table rows={rows} actions={(r: any) => <>{kind === 'invoices' && <button onClick={() => api(`/invoices/${r.id}/pdf`).then((b: Blob) => download(b, `${r.number}.pdf`))}>PDF</button>}{kind === 'quotes' && <button onClick={() => api(`/quotes/${r.id}/convert-to-bc`, { method: 'POST' }).then(load)}>Convertir BC</button>}{kind === 'purchase-orders' && <button onClick={() => api(`/purchase-orders/${r.id}/convert-to-bl`, { method: 'POST' }).then(load)}>Convertir BL</button>}</>}/></div>; }
function SettingsPage() { const [c, setC] = useState<any>({}); useEffect(() => { api('/company').then(setC); }, []); return <div className="panel"><h2>Entreprise / Fiscalité / Timbre fiscal</h2><img className="brand" src={logo} alt="Logo"/><form className="form" onSubmit={async e => { e.preventDefault(); setC(await api('/company', { method: 'PUT', body: JSON.stringify(c) })); }}>{['raisonSociale','formeJuridique','activite','adresse','wilaya','commune','telephone','email','siteWeb','nif','nis','rc','articleImposition','rib','banque','fiscalRegime'].map(f => <label key={f}>{f}<input value={c[f] || ''} onChange={e => setC({ ...c, [f]: e.target.value })}/></label>)}<p>TVA configurable: 19%, 9%, 0%, Exonéré. Timbre fiscal et régime fiscal dans les paramètres système.</p><button>Enregistrer</button></form></div>; }
function Reports() { return <div className="panel"><h2>Rapports CA, TVA, Paiements, Impayés, Clients, Produits, Factures</h2><button onClick={() => api('/reports/invoices?format=xlsx').then((b: Blob) => download(b, 'factures.xlsx'))}>Exporter XLSX</button></div>; }
function Admin() { const [logs, setLogs] = useState<any[]>([]); useEffect(() => { api('/audit-logs').then(setLogs); }, []); return <div className="panel"><h2>Utilisateurs, permissions, backup</h2><button onClick={() => api('/backup', { method: 'POST' }).then((r) => alert(JSON.stringify(r)))}>Backup database</button><Table rows={logs}/></div>; }
function Table({ rows, actions }: { rows: any[]; actions?: (r: any) => React.ReactNode }) { return <table><tbody>{rows.map(r => <tr key={r.id}>{Object.keys(r).slice(0, 9).map(k => <td key={k}>{typeof r[k] === 'object' ? r[k]?.name || '' : String(r[k])}</td>)}<td>{actions?.(r)}</td></tr>)}</tbody></table>; }
function download(blob: Blob, name: string) { const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = name; a.click(); }
function App() { const [ok, setOk] = useState(Boolean(localStorage.getItem('token'))); return ok ? <Shell/> : <Login on={() => setOk(true)}/>; }
createRoot(document.getElementById('root')!).render(<App/>);
